### PR TITLE
Feature/pre post templating

### PR DESCRIPTION
**Pull request by bdparrish**
This feature allows you to define a before and after template for inputs and groups.

### CODE REVIEW

**Comment by bdparrish** [comment]
Can you check the travis-ci build for a bad `npm install` command?  The error message doesn't lead me to believe this is the new code that I added since I did not add any new packages.

**Comment by udos86** [comment]
@bdparrish Hi!

First of all, thanks for your contribution.

I'll have to take a close look and evaluate this.

However, as you did not fully stick to the [CONTRIBUTING](https://github.com/udos86/ng-dynamic-forms/blob/master/CONTRIBUTING.md) guide, there's no chance of properly merging this pull request.

**Comment by bdparrish** [comment]
Can you explain what I am missing from the CONTRIBUTING guide?

I had to merge in `master` branch because the build would not succeed otherwise from what I could tell.

**Comment by udos86** [comment]
@bdparrish 

You should have branched off of the `development` branch.

**Comment by bdparrish** [comment]
I'll start it over if something is correct.

**Pull request closed without merging**
