### PR TITLE
Add VISIBLE/HIDDEN support for Related Form Control feature #253

### PR DESCRIPTION
**Pull request by abrathovde**
Extending Related Form Control with VISIBLE/HIDDEN.

HIDDEN removes form validation from control. VISIBLE will add validation on to control.

### CODE REVIEW

**Comment by udos86** [comment]
@abrathovde Thanks for such a comprehensive PR.

Please give me some time to evaluate this.

**Comment by abrathovde** [comment]
DynamicFormMaterialComponent tests are failing. Those tests aren't related to my pull request.

**Comment by udos86** [comment]
@abrathovde Hi!

Finally I found the time to partially merge your pull request!

Thanks, your now an official contributor to this project!

**Comment by abrathovde** [comment]
@udos86 i'm not seeing the results of my MR in the latest npm package (5.4.3).

What happened to this?
```
...
relation: [
{
 action: "HIDDEN",
 when: [
  {
  id: "some_control",
  value: "some_value"
  }
 ]
 }
]
```

It seems like you replaced it with something like this?

```
...
new DynamicInputModel(
{
 id: 'some_control',
 hidden: true
}
)
```

**Comment by udos86** [comment]
@abrathovde 

Yes, as I'm considering a total refactoring of the current implementation of related form controls I only introduced the `hidden` attribute.

**Pull request merged**
