### PR TITLE
Add support to control the 'required' property  via 'relation'

### PR DESCRIPTION
**Pull request by josemanuelduran**
Hello, 
I would like to contribute to this great forms library.
I have the need to be able to make certain fields are required conditioned by the value of other fields. 
I have also seen that the issue with this need was already created ([#708](https://github.com/udos86/ng-dynamic-forms/issues/708)), that is why I have not raised my own issue.

I have added a new possible action for the relations ('REQUIRED') so that a control can be conditionally required to the value that is given to another control, in the same way that it is done with the property 'disabled'.

resolves: #708

### CODE REVIEW

**Comment by datencia** [comment]
Would appreciate this!

**Comment by Karamuto** [comment]
Hello @josemanuelduran ,

could you please update this to the latest library version, as well as be sure that the code coverage is not decreasing?

Thanks in advance!

**Comment by jdurandoming** [comment]
Hello @Karamuto 
I have updated my branch with the latest library version, and I have tried not to decrease the test coverage, but I don't know how to do it, I have added all the changes I have seen that could increase the coverage, but I don't get it.

**Comment by josemanuelduran** [comment]
Hello @Karamuto
I have updated my branch with the latest library version, and I have tried not to decrease the test coverage, but I don't know how to do it, I have added all the changes I have seen that could increase the coverage, but I don't get it.

**Comment by Karamuto** [comment]
@josemanuelduran ,
sadly your branch has conflicts now, I will overlook the coverage as its still pretty good.

May you resolve the conflicts and I will merge it into the develop branch.

**Comment by josemanuelduran** [comment]
Hello @Karamuto,
I have merged with your development branch and I have solved the conflicts.
I can't wait for you to merge my branch, as I'm quite excited to be able to contribute to this project.

**Pull request merged**
